### ISSUE TITLE
Integrate with Clef

### ISSUE THREAD

**Issue by mahcloud** [WhosAble/WhosAble#33]
See if clef is an option for login security.
This might be nice is Clef allows the user to choose which authentication method they want.
https://getclef.com/

**Comment by dooliddler** [comment]
Excellent

**Comment by mahcloud** [comment]
Tried to integrate with Clef on another project last night just to see how easy it would be.
2 problems.
1) Clef can only integrate with an inline javascript tag which would break in our React front end because they don't have async setup properly
2) Their api only works with python, ruby, or php. I tried creating my own oauth2 integration but their service just returned a dns error.

Conclusion... not impressed

**Comment by dooliddler** [comment]
@mahcloud Sent you the text about Clef before I read this.  So, Clef integration is off the table for now.  No problem
